import{packStep}from'./pack.js';
import{resetItems,useItem,itemStep,drawItems,itemHud}from'./items.js';
import{chars,C,stat,drawSelect,drawKartRacer}from'./characters.js';
import{lapMods}from'./laps.js';
import{makeTrack,drawRoad,drawScenery}from'./track.js';
import{audioStart,audioStep}from'./audio.js';
const c=document.querySelector('#c'),x=c.getContext('2d'),TAU=Math.PI*2;
let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2),keys={},pts=new Map,steerTouch=0,accelTouch=0,brakeTouch=0,driftTouch=0,itemTap=0,itemLatch=0,choice=0,selecting=1,lastPick=-1,help=0,coarse=matchMedia('(pointer:coarse)').matches;
function resize(){W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function choose(){audioStart();selecting=0;reset(choice)}
addEventListener('keydown',e=>{if(selecting){if(['ArrowLeft','KeyA'].includes(e.code))choice=(choice+5)%6;if(['ArrowRight','KeyD'].includes(e.code))choice=(choice+1)%6;if(['Enter','Space'].includes(e.code))choose();e.preventDefault();return}keys[e.code]=1;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();if(e.code==='KeyH')help=help>0?0:6;if(e.code==='KeyR'&&finished){seed=(Math.random()*2**31)|0;seg=makeTrack(seed,N);reset(choice)}if(e.code==='KeyC'&&finished)selecting=1});
addEventListener('keyup',e=>keys[e.code]=0);
c.addEventListener('pointerdown',e=>{if(selecting){let k=Math.max(0,Math.min(5,~~(e.clientX/W*6)));if(k==lastPick)choose();else{choice=k;lastPick=k}return}pts.set(e.pointerId,[e.clientX,e.clientY]);c.setPointerCapture(e.pointerId);pointer(e,1)});c.addEventListener('pointermove',e=>{if(!selecting&&pts.has(e.pointerId)){pts.set(e.pointerId,[e.clientX,e.clientY]);pointer(e,0)}});c.addEventListener('pointerup',e=>{pts.delete(e.pointerId);touchState()});c.addEventListener('pointercancel',e=>{pts.delete(e.pointerId);touchState()});
function touchState(){steerTouch=0;accelTouch=brakeTouch=driftTouch=0;for(let[,p]of pts){let px=p[0]/W,py=p[1]/H;if(px<.55)steerTouch=Math.max(-1,Math.min(1,(px/.55-.5)*2));else if(py>.72){if(px>.72)accelTouch=1;else brakeTouch=1}else if(py>.48)driftTouch=1}}
function pointer(e,down){let px=e.clientX/W,py=e.clientY/H;if(down&&px>.72&&py<.3)itemTap=1;touchState()}
const N=768,L=105,DRAW=205,CAMBACK=2.2,T={steer:22,accel:3.1,jump:6.6,bank:.14,edge:1.18,airCam:.12,kartScale:1};
let seg=[],seed=0x13A7C,t0=performance.now(),count=3.6,finished=0,cam={lag:0,pitch:0},fx=[],flash=0,view=[],rivals=[],player;
function P(k=choice){let q={z:0,x:0,v:0,lat:0,steer:0,yaw:0,drift:0,driftDir:0,driftTime:0,driftCool:0,charge:0,beat:0,boost:0,lap:1,fall:0,resp:0,chain:0,air:0,vy:0,item:null,kind:k,hop:0};q.h=chars[k].h;return q}
function makeRivals(){let total=N*L,start=[7*L,9*L,11*L,total-L*.9,total-L*1.8],pool=chars.map((q,k)=>[q,k]).filter(q=>q[1]!=player.kind);rivals=pool.map((d,i)=>({h:d[0].h,kind:d[1],z:start[i],x:(i%2?-.32:.32)+(i==4?-.08:0),v:0,lat:0,yaw:0,drift:0,lap:i<3?1:0,hit:0,phase:i*1.73,base:(1720+(i%3)*65)*d[0].speed,item:null}))}
function score(r){return r.lap*N*L+r.z}function place(){let q=1,ps=score(player);for(let r of rivals)if(score(r)>ps)q++;return q}
function burst(px,py,n,hue=0,power=1){for(let i=0;i<n;i++){let a=Math.random()*TAU,s=(20+Math.random()*90)*power;fx.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s-20,l:.3+Math.random()*.35,h:(hue+i*19)%360,z:1+Math.random()*3})}}
function particles(dt){x.save();x.globalCompositeOperation='lighter';for(let i=fx.length-1;i>=0;i--){let p=fx[i];p.l-=dt;if(p.l<=0){fx.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=70*dt;x.fillStyle=`hsla(${p.h},100%,65%,${Math.min(1,p.l*2)})`;x.fillRect(p.x,p.y,p.z,p.z*2)}x.restore()}
function relative(z){let total=N*L,d=z-player.z;if(d>total/2)d-=total;if(d<-total/2)d+=total;return d}
function projectRel(rel){let vr=rel+CAMBACK*L;if(vr<0)return null;let f=vr/L,i=Math.floor(f),u=Math.max(0,Math.min(1,f-i)),a=view[i],b=view[i+1];if(!a){for(let k=i;k>=0&&!a;k--)a=view[k]}if(!b){for(let k=i+1;k<view.length&&!b;k++)b=view[k]}if(!a&&!b)return null;if(!a)a=b;if(!b)b=a;return{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u,w:a.w+(b.w-a.w)*u,bank:a.bank+(b.bank-a.bank)*u,pitch:(a.pitch||0)+((b.pitch||0)-(a.pitch||0))*u,p:(a.p||0)+((b.p||a.p||0)-(a.p||0))*u,s:b.s||a.s}}
function drawRivals(){let list=[];for(let r of rivals){let rel=relative(r.z);if(rel>DRAW*L||rel<-CAMBACK*L)continue;let p=projectRel(rel);if(p)list.push([rel,r,p])}list.sort((a,b)=>b[0]-a[0]);for(let[,r,p]of list){let depth=p.p||1,sc=Math.max(.18,Math.min(1.1,depth*1.08)),xx=p.x+r.x*p.w*.56,ground=p.y-r.x*p.bank*p.w*T.bank*.56,yy=ground-44*sc;x.save();x.translate(xx,yy);x.rotate(-p.bank*T.bank);x.translate(0,-(p.pitch||0)*5);drawKartRacer(x,r,sc,{yaw:r.yaw*1.12,drift:r.drift,bank:p.bank,hit:(r.hit||0)*(r.bump||0)});x.restore()}}
function sprite(){let c0=view.contact||projectRel(0)||{x:W/2,y:H*.9,w:W*.4,bank:0,pitch:0},xx=c0.x+player.x*c0.w*.56,sz=Math.max(.88,Math.min(1.04,H/700))*T.kartScale,ground=c0.y-player.x*c0.bank*c0.w*T.bank*.56,pitch=c0.pitch||0;cam.riderY=cam.riderY==null?ground:cam.riderY+(ground-cam.riderY)*.32;cam.riderBank=cam.riderBank==null?c0.bank:cam.riderBank+(c0.bank-cam.riderBank)*.28;cam.riderPitch=cam.riderPitch==null?pitch:cam.riderPitch+(pitch-cam.riderPitch)*.25;xx=Math.round(xx*2)/2;let y=Math.round((cam.riderY-44*sz-cam.riderPitch*6*sz-player.air*H*.095-player.hop*7)*2)/2;player.sx=xx;player.sy=y;let pose={yaw:player.yaw*1.22,lean:-player.lat*.2,drift:player.drift,bank:cam.riderBank,air:player.air,hit:(player.hurt||0)*(player.hitSide||0)};x.save();x.translate(xx,y);x.rotate(-cam.riderBank*T.bank-cam.riderPitch*.015);if(player.boost>0||player.chain>40){x.globalCompositeOperation='lighter';for(let i=0;i<4;i++){x.strokeStyle=`hsla(${player.kind==5?(performance.now()*.12+i*55)%360:C(player).h},100%,70%,${.07+player.chain*.0009})`;x.lineWidth=2+i;x.beginPath();x.moveTo(-15-i*7,32+i*4);x.lineTo(-29-i*13,60+i*7);x.moveTo(15+i*7,32+i*4);x.lineTo(29+i*13,60+i*7);x.stroke()}x.globalCompositeOperation='source-over'}drawKartRacer(x,player,sz,pose);x.restore();if(player.drift){let stage=player.charge>.72?2:player.charge>.38?1:0,hh=stage==2?(performance.now()*.4)%360:stage?190:40;for(let i=0;i<3;i++)fx.push({x:xx+(i%2?32:-32),y:y+39+i*3,vx:(Math.random()-.5)*85,vy:-35-Math.random()*55,l:.22+Math.random()*.16,h:hh,z:2+stage})}}
function moveRivals(dt){let total=N*L,t=performance.now()*.001;for(let r of rivals){r.hit=Math.max(0,r.hit-dt);let si=~~(r.z/L)%N,ss=seg[si],lm=lapMods(r.lap||1,si,ss),curve=ss.c,target=Math.max(-.62*lm.w,Math.min(.62*lm.w,-curve*.18+Math.sin(t*.52+r.phase)*.22));let delta=target-r.x;r.lat+=delta*dt*2.4;r.lat*=Math.pow(.08,dt);r.x+=r.lat*dt;r.drift=Math.abs(curve)>.55&&Math.abs(delta)>.08;r.yaw+=(Math.max(-.5,Math.min(.5,delta*2.1+(r.drift?Math.sign(delta)*.22:0)))-r.yaw)*Math.min(1,dt*9);let pace=r.base+Math.sin(t*.8+r.phase)*35+(r.lap==3?28:0);r.v+=(pace-r.v)*dt*1.4;r.z+=r.v*dt;if(r.z>=total){r.z-=total;r.lap++}let ni=~~(r.z/L)%N,q=seg[ni];q.col=r.h;q.ink=Math.min(1,q.ink+.05*stat(r,'paint'));q.px+=(r.x-q.px)*.2;let dz=r.z-player.z;if(dz>total/2)dz-=total;if(dz<-total/2)dz+=total;if(Math.abs(dz)<72&&Math.abs(r.x-player.x)<.25&&!r.hit&&!player.air&&!player.fall){let side=Math.sign(player.x-r.x)||1,impact=Math.min(1,.35+Math.abs(player.v-r.v)/700),mid=(player.v+r.v)*.5;player.x+=side*.045;r.x-=side*.11;player.lat+=side*(.28+impact*.3)*stat(r,'shove');r.lat=(r.lat||0)-side*(.16+impact*.2)*stat(player,'shove');player.v=mid+(player.v-mid)*.55;r.v=mid+(r.v-mid)*.55;player.hurt=Math.max(player.hurt||0,.12);player.hitSide=side;r.hit=.26+.18*impact;r.bump=-side;flash=Math.max(flash,.13);burst(W/2+player.x*W*.22,H*.81,9,(r.h+C(player).h)*.5,.7)}}}
function panel(px,py,w,h,accent){x.fillStyle='rgba(14,10,35,.72)';x.beginPath();x.roundRect(px,py,w,h,12);x.fill();x.strokeStyle=`hsla(${accent},90%,72%,.45)`;x.lineWidth=2;x.stroke()}
function controls(){if(!(count>0||help>0||coarse))return;let a=Math.min(1,count>0?1:help/2),hue=C(player).h;x.save();x.globalAlpha=coarse?.68:a;if(coarse){let b=[[W*.84,H*.82,'A','ACCEL'],[W*.64,H*.82,'B','BRAKE'],[W*.84,H*.59,'R','DRIFT'],[W*.84,H*.16,'L','ITEM']];for(let q of b){x.fillStyle='rgba(12,9,31,.54)';x.beginPath();x.arc(q[0],q[1],28,0,TAU);x.fill();x.strokeStyle=`hsla(${hue},90%,75%,.5)`;x.stroke();x.textAlign='center';x.fillStyle='#fff';x.font='1000 13px system-ui';x.fillText(q[2],q[0],q[1]-8);x.font='700 7px system-ui';x.fillText(q[3],q[0],q[1]+9)}x.textAlign='left';x.restore();return}let w=Math.min(690,W*.84),px=W/2-w/2,py=H*.89;x.fillStyle='rgba(12,9,31,.76)';x.beginPath();x.roundRect(px,py,w,48,12);x.fill();x.strokeStyle=`hsla(${hue},90%,75%,.35)`;x.stroke();x.textAlign='center';x.fillStyle='#fff';x.font='900 10px system-ui';x.fillText('WASD/ARROWS · SPACE DRIFT · E ITEM · H HELP',W/2,py+18);x.textAlign='left';x.restore()}
function hud(){let cc=C(player),hue=player.kind==5?performance.now()*.08%360:cc.h,pos=place();x.textBaseline='top';panel(14,14,112,58,hue);x.fillStyle='rgba(255,255,255,.62)';x.font='800 10px system-ui';x.fillText('LAP',28,24);x.fillStyle='#fff';x.font='1000 26px system-ui';x.fillText(`${Math.min(player.lap,3)} / 3`,27,37);let pw=116;panel(W-pw-14,14,pw,76,hue);x.textAlign='right';x.fillStyle='rgba(255,255,255,.62)';x.font='800 10px system-ui';x.fillText('POSITION',W-27,24);x.fillStyle='#fff';x.font='1000 34px system-ui';x.fillText(`${pos} / 6`,W-27,36);x.font='800 11px system-ui';x.fillStyle='#dce4ff';x.fillText(`${Math.round(player.v*.085)} km/h`,W-27,72);x.textAlign='left';let bw=Math.min(255,W*.36),py=H-49;panel(14,H-82,bw+28,67,hue);x.fillStyle=`hsl(${hue} 100% 76%)`;x.font='1000 12px system-ui';x.fillText(cc.name,27,H-70);x.fillStyle='rgba(255,255,255,.14)';x.beginPath();x.roundRect(27,py,bw,9,5);x.fill();x.fillStyle=`hsl(${hue} 100% 64%)`;x.beginPath();x.roundRect(27,py,bw*Math.min(1,player.chain/100),9,5);x.fill();x.fillStyle='rgba(255,255,255,.72)';x.font='800 9px system-ui';x.fillText(`MOMENTUM ${player.chain|0}%`,27,H-34);if(player.drift){let s=player.charge>.72?'PRISM TURBO':player.charge>.38?'SUPER DRIFT':'DRIFT';x.textAlign='center';x.font=`1000 ${Math.max(15,W*.018)}px system-ui`;x.fillStyle=player.charge>.72?`hsl(${performance.now()*.2%360} 100% 75%)`:player.charge>.38?'#80e8ff':'#ffd75b';x.fillText(`${s}  ${'◆'.repeat(Math.min(3,player.beat))}${'◇'.repeat(3-Math.min(3,player.beat))}`,W/2,H*.66);x.textAlign='left'}if(count>0){x.textAlign='center';x.font=`1000 ${Math.min(88,W*.15)}px system-ui`;x.fillStyle='#fff';let m=count>2.5?'READY':count>1.5?'SET':count>.5?'CHEAT':'GO!';x.shadowBlur=18;x.shadowColor=`hsl(${hue} 100% 65%)`;x.fillText(m,W/2,H*.22);x.shadowBlur=0;x.textAlign='left'}if(player.fall){x.textAlign='center';x.font=`1000 ${Math.min(48,W*.08)}px system-ui`;x.fillText('PRISM SNAP',W/2,H*.42);x.textAlign='left'}itemHud(x,W,H,player);controls();if(finished){x.fillStyle='rgba(9,5,26,.8)';x.fillRect(0,0,W,H);x.textAlign='center';x.font=`1000 ${Math.min(64,W*.1)}px system-ui`;x.fillStyle='#fff';x.fillText(`FINISH ${finished}/6`,W/2,H*.3);x.font=`800 ${Math.min(22,W*.04)}px system-ui`;x.fillText('R RETRY · C RACER',W/2,H*.43);x.textAlign='left'}}
function reset(k=choice){player=P(k);makeRivals();resetItems(N,L,seed);itemLatch=itemTap=0;count=3.6;finished=0;cam.lag=cam.pitch=0;cam.riderY=cam.riderBank=cam.riderPitch=null;cam.boostFx=0;cam.worldYaw=null;help=5;t0=performance.now()}
function drive(dt){let raw=(keys.ArrowLeft||keys.KeyA?-1:0)+(keys.ArrowRight||keys.KeyD?1:0)+steerTouch,driftBtn=keys.Space||driftTouch,gas=keys.ArrowUp||keys.KeyW||accelTouch,brake=keys.ArrowDown||keys.KeyS||brakeTouch;raw=Math.max(-1,Math.min(1,raw));player.steer+=(raw-player.steer)*Math.min(1,dt*T.steer);let si=~~(player.z/L)%N,s=seg[si],lm=lapMods(player.lap,si,s),speedN=Math.min(1.1,player.v/1950),turn=player.steer,spd=stat(player,'speed'),target=player.boost>0?2825*spd:gas?1950*spd:0;if(brake)target=0;let rate=player.boost>0?5.4:gas?T.accel:brake?6:.32;player.v+=(target-player.v)*Math.min(1,dt*rate);if(!gas&&!player.boost&&player.v<10)player.v=0;player.boost=Math.max(0,player.boost-dt);player.hop*=Math.pow(.035,dt);
 player.driftCool=Math.max(0,(player.driftCool||0)-dt);let driftHold=driftBtn&&player.v>700&&!player.air&&!player.fall&&(player.drift||player.driftCool<=0);
 if(driftHold&&(player.drift||Math.abs(turn)>.34)){if(!player.drift){player.drift=1;player.driftDir=Math.sign(turn);player.driftTime=0;player.charge=0;player.beat=0;player.hop=1;burst(W/2+player.x*W*.22,H*.82,6,50,.5)}player.driftTime+=dt;let align=turn*player.driftDir,quality=align>=0?.42+Math.abs(turn)*.58:.12*Math.max(0,1-Math.abs(turn));if(player.driftTime>.24)player.charge=Math.min(1,player.charge+dt*(.27+quality*.5)*stat(player,'drift'));else player.charge=Math.max(0,player.charge-dt*.12);let gate=player.beat==0?.32:player.beat==1?.62:.9;if(player.charge>=gate&&player.beat<3){player.beat++;player.chain=Math.min(100,player.chain+(3+player.beat*2)*stat(player,'charge'));burst(W/2+player.x*W*.22,H*.82,7,player.beat==3?300:player.beat==2?190:45,.7)}}else if(player.drift){let earned=player.driftTime>.45&&player.charge>.3&&player.v>650;if(earned){let power=.1+Math.max(0,player.charge-.28)*.52+player.beat*.05;player.boost=Math.max(player.boost,power);player.chain=Math.min(100,player.chain+(player.charge*8+player.beat*2)*stat(player,'charge'));flash=.25;burst(W/2+player.x*W*.22,H*.82,11,player.beat==3?300:C(player).h,.9)}player.driftCool=earned?.34:.18;player.drift=0;player.driftTime=0;player.charge=0;player.beat=0;player.driftDir=0}
 let curveForce=s.c*speedN*speedN*.46,desired=player.drift?player.driftDir*(.92+speedN*.38)+turn*.42:turn*(.5+speedN*.35);desired-=curveForce;player.lat+=(desired-player.lat)*Math.min(1,dt*(player.drift?7.5:15));player.x+=player.lat*dt*(player.drift?1.12:1);let yawTarget=turn*.34+(player.drift?player.driftDir*(.64+player.charge*.18):0)+player.lat*.045;player.yaw+=(yawTarget-player.yaw)*Math.min(1,dt*(player.drift?13:20));let edgeAt=.82*lm.w*stat(player,'edge'),fallAt=1.2*lm.w*stat(player,'edge');player.edge=Math.max(0,Math.abs(player.x)-edgeAt);if(player.edge>0&&!player.air){let save=player.drift?.32:1;player.lat-=Math.sign(player.x)*player.edge*dt*T.edge*4*stat(player,'edge')*save;player.v*=Math.max(player.drift?.985:.97,1-player.edge*dt*(player.drift?.12:.26))}player.chain=Math.max(0,player.chain-dt*(player.drift?1:3.1));let old=si,total=N*L;player.z+=player.v*dt*(1+player.chain*.0025);if(player.z>=total){player.z-=total;player.lap++;if(player.lap>3)finished=place();else{flash=.58;burst(W/2,H*.45,28,C(player).h,1.1)}}let ni=~~(player.z/L)%N,ns=seg[ni],prev=seg[(ni-1+N)%N],m=lapMods(player.lap,ni,ns),pm=lapMods(player.lap,(ni-1+N)%N,prev);ns.col=C(player).h;ns.ink=Math.min(1,ns.ink+(.07+player.chain*.001)*stat(player,'paint'));ns.px+=(player.x-ns.px)*.25;if(ni!=old&&m.event==1&&pm.event!=1&&!player.air){player.boost=Math.max(player.boost,.46);player.chain=Math.min(100,player.chain+7);flash=.25;burst(W/2+player.x*W*.22,H*.83,14,190,1.1)}if(ni!=old&&ns.jump&&prev.ramp&&!player.air&&Math.abs(player.x-(ns.rampX||0))<.32){player.air=.02;player.vy=3.25+player.v/1100;player.chain=Math.min(100,player.chain+4);burst(W/2+player.x*W*.22,H*.83,10,35,.8)}if(player.air){player.air+=player.vy*dt;player.vy-=T.jump*dt;if(player.air<=0){let perfect=Math.abs(player.yaw)<.38&&Math.abs(player.x)<.9*m.w;player.air=0;player.vy=0;if(perfect){player.boost=Math.max(player.boost,.3);player.chain=Math.min(100,player.chain+11);flash=.3;burst(W/2+player.x*W*.22,H*.82,15,120,1)}else player.v*=.95}}if(Math.abs(player.x)>fallAt&&!player.fall&&!player.air){player.fall=1;player.resp=.58;player.v*=.6;burst(W/2+player.x*W*.22,H*.78,22,C(player).h,1.2)}if(player.fall){player.resp-=dt;if(player.resp<=0){player.fall=0;player.x=Math.sign(player.x)*.12;player.lat=-Math.sign(player.x)*.18;player.yaw=0;player.v=Math.max(player.v,1050);player.chain*=.4;flash=.5}}
 moveRivals(dt);flash=Math.max(flash,packStep(dt,{player,rivals,N,L,burst,W,H}));flash=Math.max(flash,itemStep(dt,{player,rivals,N,L,burst,W,H,rank:place()}));let fire=keys.KeyE||keys.ControlLeft||keys.ControlRight||itemTap;if(fire&&!itemLatch)flash=Math.max(flash,useItem({player,rivals,N,L,burst,W,H}));itemLatch=!!fire;itemTap=0}
function speedFX(){let b=cam.boostFx||0;if(b<.03)return;x.save();let vx=W/2-cam.lag*.2,vy=H*.34;x.globalCompositeOperation='lighter';for(let i=0;i<30;i++){let a=(i/30*TAU)+Math.sin(i*17+seed)*.11,inner=.18+((i*29)%11)/80,outer=inner+.18+b*.38,r0=Math.min(W,H)*inner,r1=Math.max(W,H)*outer,ax=Math.cos(a),ay=Math.sin(a)*.72;x.strokeStyle=`hsla(${(C(player).h+i*13)%360},100%,82%,${.03+b*.22})`;x.lineWidth=1+b*2.2;x.beginPath();x.moveTo(vx+ax*r0,vy+ay*r0);x.lineTo(vx+ax*r1,vy+ay*r1);x.stroke()}let g=x.createRadialGradient(vx,vy,H*.08,vx,vy,Math.max(W,H)*.7);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.58,`rgba(255,255,255,${b*.015})`);g.addColorStop(1,`hsla(${C(player).h},100%,65%,${b*.09})`);x.fillStyle=g;x.fillRect(0,0,W,H);x.restore()}
function step(now){let dt=Math.min(.033,(now-t0)/1000||.016);t0=now;if(selecting){drawSelect(x,W,H,choice);requestAnimationFrame(step);return}help=Math.max(0,help-dt);flash=Math.max(0,flash-dt*3);if(count>0){count-=dt;player.v*=.92}else if(!finished)drive(dt);audioStep(player);let base=~~(player.z/L)%N,cur=seg[base],ahead=seg[(base+7)%N],slope=Math.max(-1,Math.min(1,(ahead.y-cur.y)/520)),boostWant=Math.min(1,(player.boost||0)*2.2+Math.max(0,(player.v-2050)/850));cam.boostFx+=(boostWant-cam.boostFx)*Math.min(1,dt*(boostWant>cam.boostFx?12:5));cam.lag+=(-player.yaw*W*.003-cam.lag)*Math.min(1,dt*7);cam.pitch+=(slope*.22-player.air*T.airCam*.72-player.vy*.009-cam.pitch)*Math.min(1,dt*6);x.save();drawScenery({x,W,H,player,seg,N,L,seed,cam});view=drawRoad({x,W,H,player,seg,N,L,DRAW,T,cam,CAMBACK});drawItems({ctx:x,player,N,L,view,bank:T.bank,CAMBACK});drawRivals();if(!player.fall)sprite();particles(dt);x.restore();speedFX();if(flash){x.fillStyle=`rgba(255,255,255,${flash*.1})`;x.fillRect(0,0,W,H)}hud();requestAnimationFrame(step)}
seg=makeTrack(seed,N);player=P(0);requestAnimationFrame(step);
if(location.search.includes('dev'))import('./feel-lab.js').then(m=>m.mount(()=>player,cam,T)).catch(()=>{});
